# Horizon is an explicit platform, never a pretend Linux build.
set(DOLPHIN_HORIZON ON CACHE BOOL "Build the libnx frontend" FORCE)
foreach(feature ENABLE_QT ENABLE_NOGUI ENABLE_CLI_TOOL ENABLE_TESTS ENABLE_ALSA
    ENABLE_PULSEAUDIO ENABLE_CUBEB ENABLE_LLVM ENABLE_X11 ENABLE_EGL
    ENABLE_SDL ENABLE_AUTOUPDATE ENABLE_ANALYTICS ENCODE_FRAMEDUMPS USE_UPNP
    USE_DISCORD_PRESENCE USE_MGBA USE_RETRO_ACHIEVEMENTS)
  set(${feature} OFF CACHE BOOL "Unavailable in Horizon v0.1" FORCE)
endforeach()
set(HORIZON_RENDERER "OpenGL" CACHE STRING "Horizon driver: OpenGL or Vulkan")
set_property(CACHE HORIZON_RENDERER PROPERTY STRINGS OpenGL Vulkan)
if(HORIZON_RENDERER STREQUAL "Vulkan")
  set(ENABLE_VULKAN ON CACHE BOOL "Pinned static NXVK driver" FORCE)
  add_compile_definitions(HORIZON_VULKAN)
elseif(HORIZON_RENDERER STREQUAL "OpenGL")
  set(ENABLE_VULKAN OFF CACHE BOOL "Separate Horizon driver builds" FORCE)
else()
  message(FATAL_ERROR "HORIZON_RENDERER must be OpenGL or Vulkan")
endif()
set(USE_SYSTEM_LIBS OFF CACHE STRING "Use pinned upstream dependencies" FORCE)
set(USE_SYSTEM_CURL ON CACHE STRING "Use devkitPro curl" FORCE)
set(USE_SYSTEM_ZLIB ON CACHE STRING "Use devkitPro zlib" FORCE)
set(USE_SYSTEM_BZIP2 ON CACHE STRING "Use devkitPro bzip2" FORCE)
set(USE_SYSTEM_ICONV OFF CACHE STRING "Use Dolphin iconv" FORCE)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(datadir "sdmc:/switch/Phocoena" CACHE PATH "SD runtime data root" FORCE)
add_compile_definitions(__SWITCH__ DOLPHIN_HORIZON EGL_NO_X11 MBEDTLS_NO_PLATFORM_ENTROPY)
add_compile_definitions(MBEDTLS_USER_CONFIG_FILE="Horizon/MbedTLSConfig.h")
include_directories(SYSTEM "${DEVKITPRO}/portlibs/switch/include")
link_directories("${DEVKITPRO}/portlibs/switch/lib")
